[build]
  functions = "api"
  publish = "."

[functions]
  directory = "api"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  functions = "api"
  publish = "."
  port = 8888

# Environment variables (set these in Netlify dashboard)
# SMTP_HOST = "your-smtp-host-here"
# SMTP_USER = "your-smtp-user-here"
# SMTP_PASS = "your-smtp-pass-here"
# RECIPIENT_EMAIL = "recipient@example.com"
